/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Destination {
  'country' : string,
  'name' : string,
  'rating' : bigint,
  'price' : bigint,
}
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Service { 'name' : string, 'description' : string }
export interface TourPackage {
  'destination' : string,
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'image' : string,
  'price' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addDestination' : ActorMethod<[string, Destination], undefined>,
  'addService' : ActorMethod<[string, Service], undefined>,
  'addTourPackage' : ActorMethod<[string, TourPackage], undefined>,
  'getAllDestinations' : ActorMethod<[], Array<Destination>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTourPackages' : ActorMethod<[], Array<TourPackage>>,
  'getDestination' : ActorMethod<[string], [] | [Destination]>,
  'getGoogleSheetsWebhook' : ActorMethod<[], [] | [string]>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getService' : ActorMethod<[string], [] | [Service]>,
  'getTourPackage' : ActorMethod<[string], [] | [TourPackage]>,
  'setGoogleSheetsWebhook' : ActorMethod<[string], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];