/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Destination = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const TourPackage = IDL.Record({
  'destination' : IDL.Text,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Nat,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addDestination' : IDL.Func([IDL.Text, Destination], [], []),
  'addService' : IDL.Func([IDL.Text, Service], [], []),
  'addTourPackage' : IDL.Func([IDL.Text, TourPackage], [], []),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getDestination' : IDL.Func([IDL.Text], [IDL.Opt(Destination)], ['query']),
  'getGoogleSheetsWebhook' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getTourPackage' : IDL.Func([IDL.Text], [IDL.Opt(TourPackage)], ['query']),
  'setGoogleSheetsWebhook' : IDL.Func([IDL.Text], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Destination = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Service = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const TourPackage = IDL.Record({
    'destination' : IDL.Text,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addDestination' : IDL.Func([IDL.Text, Destination], [], []),
    'addService' : IDL.Func([IDL.Text, Service], [], []),
    'addTourPackage' : IDL.Func([IDL.Text, TourPackage], [], []),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getDestination' : IDL.Func([IDL.Text], [IDL.Opt(Destination)], ['query']),
    'getGoogleSheetsWebhook' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getTourPackage' : IDL.Func([IDL.Text], [IDL.Opt(TourPackage)], ['query']),
    'setGoogleSheetsWebhook' : IDL.Func([IDL.Text], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };